version: 2
updates:
- package-ecosystem: npm
  directory: "/site"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/site"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 10
